//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Application.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorOccurredInRegisteration {
            get {
                return ResourceManager.GetString("ErrorOccurredInRegisteration", resourceCulture);
            }
        }
        
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        internal static string AlreadyTaken {
            get {
                return ResourceManager.GetString("AlreadyTaken", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string WrongUsernameOrPassword {
            get {
                return ResourceManager.GetString("WrongUsernameOrPassword", resourceCulture);
            }
        }
        
        internal static string WrongNumberOfObjects {
            get {
                return ResourceManager.GetString("WrongNumberOfObjects", resourceCulture);
            }
        }
        
        internal static string InvalidImageFile {
            get {
                return ResourceManager.GetString("InvalidImageFile", resourceCulture);
            }
        }
        
        internal static string RequiredImage {
            get {
                return ResourceManager.GetString("RequiredImage", resourceCulture);
            }
        }
        
        internal static string EmptyImage {
            get {
                return ResourceManager.GetString("EmptyImage", resourceCulture);
            }
        }
        
        internal static string InvalidImageExtension {
            get {
                return ResourceManager.GetString("InvalidImageExtension", resourceCulture);
            }
        }
        
        internal static string MaxImageSizeExceeded {
            get {
                return ResourceManager.GetString("MaxImageSizeExceeded", resourceCulture);
            }
        }
        
        internal static string InvalidImageContent {
            get {
                return ResourceManager.GetString("InvalidImageContent", resourceCulture);
            }
        }
        
        internal static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        internal static string Rrequired {
            get {
                return ResourceManager.GetString("Rrequired", resourceCulture);
            }
        }
        
        internal static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        internal static string RequiredIsActive {
            get {
                return ResourceManager.GetString("RequiredIsActive", resourceCulture);
            }
        }
        
        internal static string InvalidActivityEnum {
            get {
                return ResourceManager.GetString("InvalidActivityEnum", resourceCulture);
            }
        }
        
        internal static string RequiredFromTime {
            get {
                return ResourceManager.GetString("RequiredFromTime", resourceCulture);
            }
        }
        
        internal static string EmptyFromTime {
            get {
                return ResourceManager.GetString("EmptyFromTime", resourceCulture);
            }
        }
        
        internal static string InvalidTimeFormat {
            get {
                return ResourceManager.GetString("InvalidTimeFormat", resourceCulture);
            }
        }
        
        internal static string FromTimeLessThanToTime {
            get {
                return ResourceManager.GetString("FromTimeLessThanToTime", resourceCulture);
            }
        }
        
        internal static string RequiredToTime {
            get {
                return ResourceManager.GetString("RequiredToTime", resourceCulture);
            }
        }
        
        internal static string EmptyToTime {
            get {
                return ResourceManager.GetString("EmptyToTime", resourceCulture);
            }
        }
        
        internal static string FromTimeNotEqualToTime {
            get {
                return ResourceManager.GetString("FromTimeNotEqualToTime", resourceCulture);
            }
        }
        
        internal static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        internal static string MinLengthUsername {
            get {
                return ResourceManager.GetString("MinLengthUsername", resourceCulture);
            }
        }
        
        internal static string MaxLengthUsername {
            get {
                return ResourceManager.GetString("MaxLengthUsername", resourceCulture);
            }
        }
        
        internal static string UsernamePattern {
            get {
                return ResourceManager.GetString("UsernamePattern", resourceCulture);
            }
        }
        
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        internal static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        internal static string PasswordUppercase {
            get {
                return ResourceManager.GetString("PasswordUppercase", resourceCulture);
            }
        }
        
        internal static string PasswordLowercase {
            get {
                return ResourceManager.GetString("PasswordLowercase", resourceCulture);
            }
        }
        
        internal static string PasswordNumber {
            get {
                return ResourceManager.GetString("PasswordNumber", resourceCulture);
            }
        }
        
        internal static string PasswordSpecial {
            get {
                return ResourceManager.GetString("PasswordSpecial", resourceCulture);
            }
        }
        
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string RequiredPhoneNumber {
            get {
                return ResourceManager.GetString("RequiredPhoneNumber", resourceCulture);
            }
        }
        
        internal static string PhoneNumberPattern {
            get {
                return ResourceManager.GetString("PhoneNumberPattern", resourceCulture);
            }
        }
        
        internal static string RequiredActivityPeriod {
            get {
                return ResourceManager.GetString("RequiredActivityPeriod", resourceCulture);
            }
        }
        
        internal static string UnavailableItemType {
            get {
                return ResourceManager.GetString("UnavailableItemType", resourceCulture);
            }
        }
        
        internal static string InvalidItemTypesCombination {
            get {
                return ResourceManager.GetString("InvalidItemTypesCombination", resourceCulture);
            }
        }
        
        internal static string PriceGreaterThanZero {
            get {
                return ResourceManager.GetString("PriceGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PriceLessThanOneBillion {
            get {
                return ResourceManager.GetString("PriceLessThanOneBillion", resourceCulture);
            }
        }
        
        internal static string PriceMustBeInteger {
            get {
                return ResourceManager.GetString("PriceMustBeInteger", resourceCulture);
            }
        }
        
        internal static string AllSeatsPositive {
            get {
                return ResourceManager.GetString("AllSeatsPositive", resourceCulture);
            }
        }
        
        internal static string DuplicateSeatNotAllowed {
            get {
                return ResourceManager.GetString("DuplicateSeatNotAllowed", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string LoginRequired {
            get {
                return ResourceManager.GetString("LoginRequired", resourceCulture);
            }
        }
    }
}
